### ISSUE TITLE
功能不是很全呢

### ISSUE THREAD

**Issue by Hosigus** [yjosx/OneForAll#1]
https://github.com/jokermonn/-Api/blob/master/ONEv3.5.0~.md#one_list
这里是Api列表

其实登陆点赞评论也可以做做嘛

**Comment by Hosigus** [comment]
readme风格蛮有意思，排版可以注意一下图片的大小，然后再多写写自己用到的技术吧

**Comment by Hosigus** [comment]
代码写的挺不错的，提一个数据类一般叫Bean，没有叫gson的，gson只是一个json解析的第三方库。

**Comment by yjosx** [comment]
> 
> 
> https://github.com/jokermonn/-Api/blob/master/ONEv3.5.0~.md#one_list
> 这里是Api列表
> 
> 其实登陆点赞评论也可以做做嘛

感谢学长的建议，这个软件的官方api并不是公开的，导致了一些功能的不全，比如登录和注册，但点赞的逻辑我将尽自己的努力尽量在下一个版本v0.3实现。目前数据类名称的问题已在v0.1.1版本修复。由于是第一次完全由自己肝的一个程序，功能差点还请多多包涵哈(´▽`ʃ♡ƪ)
